import Header from "../components/Header";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Sheyblogs - Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <Header />
        <div className="p-5">{children}</div>
      </body>
    </html>
  );
}
